# main.yml

# Workflow's name
name: Build Electron App For Windows/macOs/Ubuntu

# Workflow's trigger
on:
  push:
    tags:
      - "v*.*.*"

# Workflow's jobs
jobs:
  # job's id
  release:
    # job's name
    name: build and release electron app

    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}

    # create a build matrix for jobs
    strategy:
      fail-fast: false
      matrix:
        # os: [windows-latest, macos-latest, 'ubuntu-latest']
        # macos-13 is an intel runner, macos-14 is apple silicon
        # https://docs.github.com/zh/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14]

    # create steps
    steps:
      # step1: check out repository
      - name: Check out git repository
        uses: actions/checkout@v3

      # step2: install node env
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # step3: npm install
      - name: npm install
        run: |
          npm install

      # step4: build app for mac/win/linux
      - name: Build windows app
        if: matrix.os == 'windows-latest'
        run: |
          npm run electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build mac intl app
        if: matrix.os == 'macos-13'
        run: |
          npm run electron:build -- --x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build mac arm app
        if: matrix.os == 'macos-14'
        run: |
          npm run electron:build -- --arm64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ubuntu app
        if: matrix.os == 'ubuntu-latest'
        run: |
          npm run electron:build -- --x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for ubuntu arm64
        if: matrix.os == 'ubuntu-24.04-arm'
        run: |
          npm run electron:build -- --arm64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # step5: cleanup artifacts in dist_electron
      - name: cleanup artifacts for windows
        if: matrix.os == 'windows-latest'
        run: |
          npx rimraf "dist_electron/!(*.exe)"

      - name: cleanup artifacts for macos intel
        if: matrix.os == 'macos-13'
        run: |
          npx rimraf "dist_electron/!(*.dmg)"

      - name: cleanup artifacts for macos arm
        if: matrix.os == 'macos-14'
        run: |
          npx rimraf "dist_electron/!(*.dmg)"

      - name: cleanup artifacts for ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          npx rimraf "dist_electron/!(*.AppImage|*.deb)"

      - name: cleanup artifacts for ubuntu-24.04-arm
        if: matrix.os == 'ubuntu-24.04-arm'
        run: |
          npx rimraf "dist_electron/!(*.AppImage|*.deb)"

      # step6: upload artifacts
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: dist_electron

      # step7: create release
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: "dist_electron/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
